[package]
name = "benihime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
eframe = "0.32.3"
egui = "0.32.3"
env_logger = "0.11.8"
ignore = "0.4.23"
log = "0.4.28"
thiserror = "2.0.16"
